public class ExceptionHandling1 {


    public static void main(String args[]) {
        try
        {
            int num1 = 30, num2 = 0;
            int output = num1 / num2;
            System.out.println("Result: " + output);
        }
        catch (ArithmeticException e)
        {
            System.out.println("You Shouldn't divide a number by zero");
        }
    }
}

public class ExceptionHandling2 {

        public static void main(String args[])
        {
            try
            {
                int a[]=new int[10];
                a[11] = 9;
            }
            catch(ArrayIndexOutOfBoundsException e)
            {
                System.out.println ("ArrayIndexOutOfBounds Exception occurred");
                System.out.println ("System Message: "+e);
            }
        }
    }
    
    
    public class ExceptionHandling3 {
    public static void main(String args[])
    {
        try
        {
            int num=Integer.parseInt ("XYZ") ;
            System.out.println(num);
        }
        catch(NumberFormatException e)
        {
            System.out.println("Number format exception occurred");
        }
    }
}


public class ExceptionHandling4 {
    public static void main(String args[])
    {
        try
        {
            String str="beginnersbook";
            System.out.println(str.length());
            char c = str.charAt(40);
            System.out.println(c);
        }
        catch(StringIndexOutOfBoundsException e)
        {
            System.out.println("StringIndexOutOfBoundsException.");
        }
    }
}



public class ExceptionHandling5 {
    public static void main(String args[]) {
        try
        {
            String str = null;
            System.out.println(str.length());
        }
        catch (NullPointerException e)
        {
            System.out.println("NullPointerException..");
        }
    }
}
